begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
create function pg_temp.customer_id() returns uuid language sql as $$select '31000000-0000-4000-8000-000000000001'::uuid$$;
create function pg_temp.unit_a() returns uuid language sql security definer set search_path='' as $$select u.id from public.product_units u join public.products p on p.id=u.product_id where p.sku='TEST-A' and u.unit_name='adet'$$;
create function pg_temp.unit_case() returns uuid language sql security definer set search_path='' as $$select u.id from public.product_units u join public.products p on p.id=u.product_id where p.sku='TEST-A' and u.unit_name='koli'$$;
create function pg_temp.unit_b() returns uuid language sql security definer set search_path='' as $$select u.id from public.product_units u join public.products p on p.id=u.product_id where p.sku='TEST-B' and u.unit_name='paket'$$;
create function pg_temp.cart(q integer default 1) returns jsonb language sql as $$select jsonb_build_array(jsonb_build_object('unit_id',pg_temp.unit_a(),'quantity',q))$$;

select set_config('request.jwt.claim.sub','30000000-0000-4000-8000-000000000001',true);
set local role authenticated;
select is((select count(*) from customer_catalog(pg_temp.customer_id())),2::bigint,'Active products visible to own customer');
select is((select p->>'stock_state' from customer_catalog(pg_temp.customer_id()) p where p->>'sku'='TEST-B'),'empty','Out of stock product remains in catalog');
select ok(not exists(select 1 from customer_catalog(pg_temp.customer_id()) p where p ? 'physical_qty' or p ? 'reserved_qty'),'Customer sees stock state rather than warehouse internals');
select is((select count(*) from products),0::bigint,'Raw product access remains closed');
select throws_ok($$select * from customer_catalog('31000000-0000-4000-8000-000000000002')$$,'42501',null::text,'Customer cannot read another customer catalog');
select throws_ok($$select quote_cart('31000000-0000-4000-8000-000000000002',pg_temp.cart())$$,'42501',null::text,'Customer cannot quote another cart');
select is(quote_cart(pg_temp.customer_id(),pg_temp.cart())->>'total_kurus','10000','Cart uses backend list price');
select is((quote_cart(pg_temp.customer_id(),pg_temp.cart())->'lines'->0)->>'line_total_kurus',
 quote_product(pg_temp.customer_id(),pg_temp.unit_a(),1)->>'line_total_kurus','Cart reuses Phase 5 calculator');
select is(quote_cart(pg_temp.customer_id(),pg_temp.cart())->>'stock_sufficient','true','Available stock reported');
select is(quote_cart(pg_temp.customer_id(),pg_temp.cart(100))->>'stock_sufficient','false','Short stock reported without reservation');
select is(quote_cart(pg_temp.customer_id(),jsonb_build_array(jsonb_build_object('unit_id',pg_temp.unit_a(),'quantity',90),
 jsonb_build_object('unit_id',pg_temp.unit_case(),'quantity',1)))->>'stock_sufficient','false','Different units aggregate to same product stock demand');
select is(quote_cart(pg_temp.customer_id(),jsonb_build_array(jsonb_build_object('unit_id',pg_temp.unit_b(),'quantity',4)))->>'total_kurus','20000','Fractional conversion is exact in cart');
select throws_ok($$select quote_cart(pg_temp.customer_id(),jsonb_build_array(jsonb_build_object('unit_id',pg_temp.unit_b(),'quantity',1)))$$,'22023',null::text,'Minimum base quantity enforced');
select throws_ok($$select quote_cart(pg_temp.customer_id(),'[]')$$,'22023',null::text,'Empty checkout rejected');
select throws_ok($$select quote_cart(pg_temp.customer_id(),'{}')$$,'22023',null::text,'Object instead of items rejected');
select throws_ok($$select quote_cart(pg_temp.customer_id(),pg_temp.cart(0))$$,'22023',null::text,'Zero quantity rejected');
select throws_ok($$select quote_cart(pg_temp.customer_id(),pg_temp.cart(-1))$$,'22023',null::text,'Negative quantity rejected');
select throws_ok($$select quote_cart(pg_temp.customer_id(),jsonb_build_array(jsonb_build_object('unit_id',pg_temp.unit_a(),'quantity',1.5)))$$,'22023',null::text,'Fractional sale quantity rejected');
select throws_ok($$select quote_cart(pg_temp.customer_id(),jsonb_build_array(jsonb_build_object('unit_id',pg_temp.unit_a(),'quantity','1')))$$,'22023',null::text,'String quantity rejected');
select throws_ok($$select quote_cart(pg_temp.customer_id(),pg_temp.cart()||pg_temp.cart())$$,'22023',null::text,'Duplicate unit entries rejected');
select throws_ok($$select quote_cart(pg_temp.customer_id(),jsonb_build_array(jsonb_build_object('unit_id',pg_temp.unit_a(),'quantity',1,'price',1)))$$,'22023',null::text,'Client price not accepted');
select throws_ok($$select quote_cart(pg_temp.customer_id(),jsonb_build_array(jsonb_build_object('unit_id',pg_temp.unit_a(),'quantity',1,'discount',1)))$$,'22023',null::text,'Client discount not accepted');
select is(quote_cart(pg_temp.customer_id(),jsonb_build_array(jsonb_build_object('unit_id',pg_temp.unit_a(),'quantity',1),jsonb_build_object('unit_id',pg_temp.unit_b(),'quantity',4)))->>'fingerprint',
 quote_cart(pg_temp.customer_id(),jsonb_build_array(jsonb_build_object('unit_id',pg_temp.unit_b(),'quantity',4),jsonb_build_object('unit_id',pg_temp.unit_a(),'quantity',1)))->>'fingerprint','Cart ordering does not change quote fingerprint');
reset role;
create temp table previous_quote as select quote_cart(pg_temp.customer_id(),pg_temp.cart()) q;
update products set unit_price_kurus=10001 where sku='TEST-A';
select isnt(quote_cart(pg_temp.customer_id(),pg_temp.cart())->>'fingerprint',(select q->>'fingerprint' from previous_quote),'Price change alters quote fingerprint');
update products set unit_price_kurus=10000 where sku='TEST-A';
update product_units set conversion_to_base=2 where id=pg_temp.unit_a();
select isnt(quote_cart(pg_temp.customer_id(),pg_temp.cart())->>'fingerprint',(select q->>'fingerprint' from previous_quote),'Conversion change alters quote fingerprint');
update product_units set conversion_to_base=1 where id=pg_temp.unit_a();
update customer_pricing set discount_rate=0.5 where customer_id=pg_temp.customer_id();
select is(quote_cart(pg_temp.customer_id(),pg_temp.cart())->>'total_kurus','5000','Effective customer discount used');
select isnt(quote_cart(pg_temp.customer_id(),pg_temp.cart())->>'fingerprint',(select q->>'fingerprint' from previous_quote),'Discount change alters fingerprint');
update customer_pricing set discount_rate=0 where customer_id=pg_temp.customer_id();
update inventory set reserved_qty=physical_qty where product_id=(select id from products where sku='TEST-A');
select isnt(quote_cart(pg_temp.customer_id(),pg_temp.cart())->>'fingerprint',(select q->>'fingerprint' from previous_quote),'Stock sufficiency change alters fingerprint');
update products set active=false where sku='TEST-A';
select is((select count(*) from customer_catalog(pg_temp.customer_id())),1::bigint,'Closed product hidden');
select throws_ok($$select quote_cart(pg_temp.customer_id(),pg_temp.cart())$$,'22023',null::text,'Closed product cannot be quoted');
update products set active=true where sku='TEST-A';
update customers set assigned_sales_operator_id='30000000-0000-4000-8000-000000000002' where id=pg_temp.customer_id();
select set_config('request.jwt.claim.sub','30000000-0000-4000-8000-000000000002',true);
set local role authenticated;
select is((select count(*) from customer_catalog(pg_temp.customer_id())),2::bigint,'Assigned Sales uses shared catalog');
select is(quote_cart(pg_temp.customer_id(),pg_temp.cart())->>'total_kurus','10000','Assigned Sales receives same customer price');
select throws_ok($$select quote_cart('31000000-0000-4000-8000-000000000002',pg_temp.cart())$$,'42501',null::text,'Unassigned Sales cart denied');
reset role;
update customers set assigned_sales_operator_id=null where id=pg_temp.customer_id();
select throws_ok($$select * from customer_catalog(pg_temp.customer_id())$$,'42501',null::text,'Removed assignment closes catalog');
select set_config('request.jwt.claim.sub','30000000-0000-4000-8000-000000000003',true);
set local role authenticated;
select throws_ok($$select * from customer_catalog(pg_temp.customer_id())$$,'42501',null::text,'Warehouse price boundary preserved');
reset role;
select set_config('request.jwt.claim.sub','30000000-0000-4000-8000-000000000004',true);
set local role authenticated;
select throws_ok($$select quote_cart(pg_temp.customer_id(),pg_temp.cart())$$,'42501',null::text,'Accounting cart boundary preserved');
reset role;
select set_config('request.jwt.claim.sub','30000000-0000-4000-8000-000000000001',true);
update profiles set active=false where id=auth.uid();
set local role authenticated;
select throws_ok($$select * from customer_catalog(pg_temp.customer_id())$$,'42501',null::text,'Inactive customer denied');
reset role;
set local role anon;
select throws_ok($$select * from customer_catalog(null)$$,'42501',null::text,'Anonymous catalog denied');
select throws_ok($$select quote_cart(null,'[]')$$,'42501',null::text,'Anonymous quote denied');
reset role;


-- Restore fixture after the read-only authorization cases.
update profiles set active=true where id='30000000-0000-4000-8000-000000000001';
update inventory set reserved_qty=3 where product_id=(select id from products where sku='TEST-A');
select set_config('request.jwt.claim.sub','30000000-0000-4000-8000-000000000001',true);
create temp table checkout_state(q jsonb, result jsonb, request_key uuid);
grant all on checkout_state to authenticated;
insert into checkout_state values(quote_cart(pg_temp.customer_id(),pg_temp.cart()),null,'60000000-0000-4000-8000-000000000001');
set local role authenticated;
select lives_ok($$select save_cart_draft(pg_temp.customer_id(),pg_temp.cart())$$,'Draft can be saved');
select is(load_cart_draft(pg_temp.customer_id()),pg_temp.cart(),'Draft retains units and quantity');
select throws_ok($$select save_cart_draft('31000000-0000-4000-8000-000000000002',pg_temp.cart())$$,'42501',null::text,'Other customer draft denied');
select throws_ok($$select load_cart_draft('31000000-0000-4000-8000-000000000002')$$,'42501',null::text,'Other customer draft read denied');
reset role;
select is((select reserved_qty::text from inventory where product_id=(select id from products where sku='TEST-A')),'3','Draft reserves no stock');
update products set unit_price_kurus=11000 where sku='TEST-A';
set local role authenticated;
update checkout_state set result=checkout_cart(pg_temp.customer_id(),pg_temp.cart(),q,request_key);
select is((select result->>'outcome' from checkout_state),'changed','Changed price prevents order creation');
select is((select result->'previous_quote'->>'total_kurus' from checkout_state),'10000','Old price returned for comparison');
select is((select result->'quote'->>'total_kurus' from checkout_state),'11000','Fresh price returned for explicit approval');
reset role;
select is((select count(*) from orders where operation_key=(select request_key from checkout_state)),0::bigint,'No order written without fresh consent');
select is((select reserved_qty::text from inventory where product_id=(select id from products where sku='TEST-A')),'3','Rejected stale quote reserves nothing');
set local role authenticated;
update checkout_state set q=result->'quote';
update checkout_state set result=checkout_cart(pg_temp.customer_id(),pg_temp.cart(),q,request_key);
select is((select result->>'status' from checkout_state),'submitted','Approved current quote submits order');
select is(load_cart_draft(pg_temp.customer_id()),null::jsonb,'Matching draft removed on success');
select is(checkout_cart(pg_temp.customer_id(),pg_temp.cart(),(select q from checkout_state),(select request_key from checkout_state)),(select result from checkout_state),'Exact retry returns same receipt');
select throws_ok($$select checkout_cart(pg_temp.customer_id(),pg_temp.cart(2),(select q from checkout_state),(select request_key from checkout_state))$$,'22023',null::text,'Key cannot be reused for changed quantities');
select throws_ok($$select checkout_cart(pg_temp.customer_id(),pg_temp.cart(),(select q from checkout_state),null)$$,'22023',null::text,'Missing key rejected');
select throws_ok($$insert into orders(customer_id) values(pg_temp.customer_id())$$,'42501',null::text,'Raw order writes remain closed');
reset role;
select is((select count(*) from orders where operation_key=(select request_key from checkout_state)),1::bigint,'Retry creates one order');
select is((select count(*) from order_status_history where operation_key=(select request_key from checkout_state)),1::bigint,'Retry creates one history event');
select is((select count(*) from audit_logs where operation_key=(select request_key from checkout_state)),1::bigint,'Retry creates one audit event');
select is((select count(*) from inventory_movements where reference_id=((select result->>'order_id' from checkout_state)::uuid)),1::bigint,'Retry reserves once');
select is((select reserved_qty::text from inventory where product_id=(select id from products where sku='TEST-A')),'4','Only base quantity reserved');
select is((select physical_qty::text from inventory where product_id=(select id from products where sku='TEST-A')),'97','Submit does not pick physical stock');
select is((select payment_status from orders where operation_key=(select request_key from checkout_state)),'not_due','Submit is not debt');
select is((select credit_check_state from orders where operation_key=(select request_key from checkout_state)),'not_evaluated','Credit result is explicitly unknown');
select is((select source from orders where operation_key=(select request_key from checkout_state)),'customer_app','Customer source derived by server');
select is((select created_by from orders where operation_key=(select request_key from checkout_state)),auth.uid(),'Actor derived by server');
select is((select count(*) from payments where order_id=((select result->>'order_id' from checkout_state)::uuid)),0::bigint,'No payment fabricated');
select is((select exact_final_price_kurus_snapshot::text from order_items where order_id=((select result->>'order_id' from checkout_state)::uuid)),'11000','Exact final price stored');
update products set unit_price_kurus=12000 where sku='TEST-A';
select is((select exact_final_price_kurus_snapshot::text from order_items where order_id=((select result->>'order_id' from checkout_state)::uuid)),'11000','Later price change does not alter snapshot');
set local role authenticated;
select is(checkout_cart(pg_temp.customer_id(),pg_temp.cart(),(select q from checkout_state),(select request_key from checkout_state)),(select result from checkout_state),'Success retry ignores later catalog changes');
update checkout_state set q=quote_cart(pg_temp.customer_id(),pg_temp.cart(100)),request_key='60000000-0000-4000-8000-000000000002';
update checkout_state set result=checkout_cart(pg_temp.customer_id(),pg_temp.cart(100),q,request_key);
select is((select result->>'status' from checkout_state),'pending_approval','Short stock uses existing approval state');
reset role;
select is((select reserved_qty::text from inventory where product_id=(select id from products where sku='TEST-A')),'4','Shortage order reserves nothing');
select is((select count(*) from order_approvals where order_id=((select result->>'order_id' from checkout_state)::uuid)),1::bigint,'Shortage approval request exists');
-- Conversion and stock changes are rechecked inside the transaction.
update checkout_state set q=quote_cart(pg_temp.customer_id(),pg_temp.cart()),request_key='60000000-0000-4000-8000-000000000003';
update product_units set conversion_to_base=2 where id=pg_temp.unit_a();
set local role authenticated;
select is(checkout_cart(pg_temp.customer_id(),pg_temp.cart(),(select q from checkout_state),(select request_key from checkout_state))->>'outcome','changed','Conversion change requires new consent');
reset role;
update product_units set conversion_to_base=1 where id=pg_temp.unit_a();
update checkout_state set q=quote_cart(pg_temp.customer_id(),pg_temp.cart());
update inventory set reserved_qty=physical_qty where product_id=(select id from products where sku='TEST-A');
set local role authenticated;
select is(checkout_cart(pg_temp.customer_id(),pg_temp.cart(),(select q from checkout_state),(select request_key from checkout_state))->>'outcome','changed','Stock sufficiency change requires new consent');
reset role;
select is((select count(*) from orders where operation_key='60000000-0000-4000-8000-000000000003'),0::bigint,'No writes on conversion/stock mismatch');
-- Shared service uses assigned Sales scope, never a client-supplied actor/source.
update customers set assigned_sales_operator_id='30000000-0000-4000-8000-000000000002' where id=pg_temp.customer_id();
select set_config('request.jwt.claim.sub','30000000-0000-4000-8000-000000000002',true);
set local role authenticated;
select is(load_cart_draft(pg_temp.customer_id()),null::jsonb,'Drafts are actor scoped');
update checkout_state set q=quote_cart(pg_temp.customer_id(),pg_temp.cart()),request_key='60000000-0000-4000-8000-000000000004';
update checkout_state set result=checkout_cart(pg_temp.customer_id(),pg_temp.cart(),q,request_key);
reset role;
select is((select source from orders where operation_key=(select request_key from checkout_state)),'sales_operator','Shared service derives Sales source');
update customers set assigned_sales_operator_id=null where id=pg_temp.customer_id();
set local role authenticated;
select throws_ok($$select checkout_cart(pg_temp.customer_id(),pg_temp.cart(),(select q from checkout_state),(select request_key from checkout_state))$$,'42501',null::text,'Revoked Sales cannot replay receipt');
reset role;
select set_config('request.jwt.claim.sub','30000000-0000-4000-8000-000000000003',true);
set local role authenticated;
select throws_ok($$select checkout_cart(pg_temp.customer_id(),pg_temp.cart(),'{}',gen_random_uuid())$$,'42501',null::text,'Warehouse cannot checkout');
reset role;
select set_config('request.jwt.claim.sub','30000000-0000-4000-8000-000000000004',true);
set local role authenticated;
select throws_ok($$select checkout_cart(pg_temp.customer_id(),pg_temp.cart(),'{}',gen_random_uuid())$$,'42501',null::text,'Accounting cannot checkout');
reset role;
set local role anon;
select throws_ok($$select checkout_cart(null,'[]','{}',gen_random_uuid())$$,'42501',null::text,'Anonymous checkout denied');
reset role;


select set_config('request.jwt.claim.sub','30000000-0000-4000-8000-000000000001',true);
update products set unit_price_kurus=1 where sku in ('TEST-A','TEST-B');
update customer_pricing set discount_rate=0.5 where customer_id=pg_temp.customer_id();
create temp table fractional_cart as select pg_temp.cart()||jsonb_build_array(jsonb_build_object('unit_id',pg_temp.unit_b(),'quantity',4)) items;
grant select on fractional_cart to authenticated;
set local role authenticated;
update checkout_state set q=quote_cart(pg_temp.customer_id(),(select items from fractional_cart)),request_key='60000000-0000-4000-8000-000000000005';
update checkout_state set result=checkout_cart(pg_temp.customer_id(),(select items from fractional_cart),q,request_key);
reset role;
select is((select total_kurus from orders where operation_key=(select request_key from checkout_state)),2::bigint,'Sum rounded lines, not rounded whole cart');
select is((select exact_final_price_kurus_snapshot from order_items where order_id=((select result->>'order_id' from checkout_state)::uuid) and product_unit_id=pg_temp.unit_b()),0.125::numeric,'Sub-kurus final unit snapshot retained exactly');
select is((select final_unit_price_kurus from order_items where order_id=((select result->>'order_id' from checkout_state)::uuid) and product_unit_id=pg_temp.unit_b()),0::bigint,'Legacy rounded unit zero does not zero the actual line');
select is((select line_total_kurus from order_items where order_id=((select result->>'order_id' from checkout_state)::uuid) and product_unit_id=pg_temp.unit_b()),1::bigint,'Half-up applies at line end');
select is((select conversion_to_base_snapshot::numeric from order_items where order_id=((select result->>'order_id' from checkout_state)::uuid) and product_unit_id=pg_temp.unit_b()),0.25::numeric,'Conversion stored without rounding');
-- Failure after stock update rolls back the whole checkout, including history.
update inventory set reserved_qty=4 where product_id=(select id from products where sku='TEST-A');
create function pg_temp.reject_checkout_audit() returns trigger language plpgsql as $$begin if new.action='order_status_changed' then raise exception using errcode='23514',message='Synthetic audit failure';end if;return new;end$$;
create trigger synthetic_checkout_failure before insert on audit_logs for each row execute function pg_temp.reject_checkout_audit();
set local role authenticated;
select throws_ok($$select checkout_cart(pg_temp.customer_id(),pg_temp.cart(),quote_cart(pg_temp.customer_id(),pg_temp.cart()),'60000000-0000-4000-8000-000000000006')$$,'23514','Synthetic audit failure','Late failure rolls entire transaction back');
reset role;
select is((select count(*) from orders where operation_key='60000000-0000-4000-8000-000000000006'),0::bigint,'Failed transaction leaves no order');
select is((select count(*) from order_status_history where operation_key='60000000-0000-4000-8000-000000000006'),0::bigint,'Failed transaction leaves no history');
select is((select reserved_qty::text from inventory where product_id=(select id from products where sku='TEST-A')),'4','Failed transaction restores stock');
drop trigger synthetic_checkout_failure on audit_logs;
select is((select count(*) from audit_logs where action='stock_movement' and entity_id in(select id from inventory_movements where reference_type='order' and reference_id in(select order_id from private.checkout_receipts))),1::bigint,'Reservation is audited once');
set local role authenticated;
select throws_ok($$select * from private.checkout_receipts$$,'42501',null::text,'Receipt table is not exposed to client');
select throws_ok($$select * from private.cart_drafts$$,'42501',null::text,'Draft table is not exposed to client');
reset role;
update profiles set active=false where id=auth.uid();
set local role authenticated;
select throws_ok($$select checkout_cart(pg_temp.customer_id(),pg_temp.cart(),'{}',gen_random_uuid())$$,'42501',null::text,'Inactive customer cannot submit');
reset role;
select * from finish();
rollback;
