begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
create function pg_temp.customer_id() returns uuid language sql as $$select '31000000-0000-4000-8000-000000000001'::uuid$$;
create function pg_temp.cart() returns jsonb language sql security definer set search_path='' as $$
 select jsonb_agg(jsonb_build_object('unit_id',u.id,'quantity',1) order by u.id)
 from public.product_units u join public.products p on p.id=u.product_id where p.sku='TEST-A'
$$;
create temp table workflow_state(name text primary key,order_id uuid,key uuid default gen_random_uuid(),result jsonb,snapshot jsonb);
grant all on workflow_state to authenticated;
update customers set assigned_sales_operator_id='30000000-0000-4000-8000-000000000002' where id=pg_temp.customer_id();
select set_config('request.jwt.claim.sub','30000000-0000-4000-8000-000000000001',true);
set local role authenticated;
insert into workflow_state(name,order_id) values
 ('cancel',(checkout_cart(pg_temp.customer_id(),pg_temp.cart(),quote_cart(pg_temp.customer_id(),pg_temp.cart()),gen_random_uuid())->>'order_id')::uuid),
 ('request',(checkout_cart(pg_temp.customer_id(),pg_temp.cart(),quote_cart(pg_temp.customer_id(),pg_temp.cart()),gen_random_uuid())->>'order_id')::uuid);
update workflow_state s set snapshot=(select jsonb_agg(to_jsonb(i) order by id) from order_items i where i.order_id=s.order_id);
select is(order_workflow_state((select order_id from workflow_state where name='cancel'))->>'status','submitted','Customer reads own workflow');
select throws_ok($$select request_order_action((select order_id from workflow_state where name='cancel'),'cancel_submitted',' ',gen_random_uuid())$$,'22023',null::text,'Blank reason denied');
select throws_ok($$select request_order_action((select order_id from workflow_state where name='cancel'),'approve','test',gen_random_uuid())$$,'22023',null::text,'Undefined approval action denied');
select throws_ok($$select request_order_action((select order_id from workflow_state where name='cancel'),'request_cancel','test',gen_random_uuid())$$,'23514',null::text,'Submitted cancellation is direct, not a misleading request');
select throws_ok($$update orders set status='cancelled'$$,'42501',null::text,'Raw status update denied');
update workflow_state set result=request_order_action(order_id,'cancel_submitted','Customer cancellation',key) where name='cancel';
select is((select result->>'outcome' from workflow_state where name='cancel'),'cancelled','Submitted cancellation succeeds');
select is(request_order_action(order_id,'cancel_submitted','Customer cancellation',key),result,'Same-key retry returns original result') from workflow_state where name='cancel';
select throws_ok($$select request_order_action(order_id,'cancel_submitted','Different',key) from workflow_state where name='cancel'$$,'22023',null::text,'Different payload cannot reuse key');
select throws_ok($$select request_order_action(order_id,'cancel_submitted','Customer cancellation',gen_random_uuid()) from workflow_state where name='cancel'$$,'23514',null::text,'New key cannot cancel twice');
select is((select jsonb_agg(to_jsonb(i) order by id) from order_items i where i.order_id=s.order_id),s.snapshot,'All item and exact price snapshots unchanged') from workflow_state s where name='cancel';
select is((select payment_status from orders where id=s.order_id),'not_due','Cancellation creates no debt/payment state') from workflow_state s where name='cancel';
select is((select credit_check_state from orders where id=s.order_id),'not_evaluated','No exposure calculation added') from workflow_state s where name='cancel';
reset role;
select is((select reserved_qty::numeric from inventory i join products p on p.id=i.product_id where p.sku='TEST-A'),16::numeric,'Only this order releases 1 adet plus 1 koli; other reservation stays');
select is((select physical_qty::numeric from inventory i join products p on p.id=i.product_id where p.sku='TEST-A'),97::numeric,'Physical stock unchanged');
select is((select count(*) from inventory_movements where type='released' and reference_id=s.order_id),2::bigint,'One release for each unit item, not repeated') from workflow_state s where name='cancel';
select is((select sum(reserved_delta) from inventory_movements where order_item_id in(select id from order_items where order_id=s.order_id)),0::numeric,'Reservation movements net to zero') from workflow_state s where name='cancel';
select is((select count(*) from order_status_history where order_id=s.order_id and to_status='cancelled'),1::bigint,'Cancellation history once') from workflow_state s where name='cancel';
select is((select count(*) from audit_logs where entity_id=s.order_id and action='order_status_changed'),2::bigint,'Submit plus cancellation audited') from workflow_state s where name='cancel';
select is((select changed_by from order_status_history where operation_key=s.key),auth.uid(),'Cancellation records actor') from workflow_state s where name='cancel';
set local role authenticated;
update workflow_state set result=request_order_action(order_id,'request_change','Quantity request',key) where name='request';
select is((select result->>'outcome' from workflow_state where name='request'),'requested','Change intent recorded');
select is(request_order_action(order_id,'request_change','Quantity request',key),result,'Request same-key retry is idempotent') from workflow_state where name='request';
select is(request_order_action(order_id,'request_change','Quantity request',gen_random_uuid()),result,'Lost local key does not duplicate identical pending intent') from workflow_state where name='request';
select is(jsonb_array_length(order_workflow_state(order_id)->'requests'),1,'Request visible in scoped projection') from workflow_state where name='request';
select is(order_workflow_state(order_id)->>'status','submitted','Request does not advance order') from workflow_state where name='request';
select is((select jsonb_agg(to_jsonb(i) order by id) from order_items i where i.order_id=s.order_id),s.snapshot,'Request does not revise snapshots') from workflow_state s where name='request';
select throws_ok($$insert into order_change_requests(order_id,type,requested_by,reason,status) select order_id,'change',auth.uid(),'Raw','pending' from workflow_state limit 1$$,'42501',null::text,'Raw request insert denied');
reset role;
select is((select count(*) from order_change_requests where order_id=s.order_id),1::bigint,'Exactly one request stored') from workflow_state s where name='request';
select is((select count(*) from audit_logs where entity_id=s.order_id),1::bigint,'Intent does not invent audit event or change status') from workflow_state s where name='request';
update orders set status='picking' where id=(select order_id from workflow_state where name='request');
set local role authenticated;
select lives_ok($$select request_order_action(order_id,'request_cancel','Picking cancellation request',gen_random_uuid()) from workflow_state where name='request'$$,'Picking cancellation intent permitted');
select throws_ok($$select request_order_action(order_id,'cancel_submitted','No direct picking cancellation',gen_random_uuid()) from workflow_state where name='request'$$,'23514',null::text,'Picking cannot cancel directly');
reset role;
select is((select reserved_qty::numeric from inventory i join products p on p.id=i.product_id where p.sku='TEST-A'),16::numeric,'Picking request does not touch reservation');
update orders set status='delivered' where id=(select order_id from workflow_state where name='request');
set local role authenticated;
select throws_ok($$select request_order_action(order_id,'request_cancel','No cancellation after delivery',gen_random_uuid()) from workflow_state where name='request'$$,'23514',null::text,'Delivered requires separate return/dispute decision');
select set_config('request.jwt.claim.sub','30000000-0000-4000-8000-000000000008',true);
select throws_ok($$select order_workflow_state(order_id) from workflow_state limit 1$$,'42501',null::text,'Other customer cannot read workflow');
select throws_ok($$select request_order_action(order_id,'request_change','Unauthorized',gen_random_uuid()) from workflow_state limit 1$$,'42501',null::text,'Other customer cannot act');
select set_config('request.jwt.claim.sub','30000000-0000-4000-8000-000000000002',true);
select lives_ok($$select order_workflow_state(order_id) from workflow_state limit 1$$,'Assigned Sales reads workflow');
insert into workflow_state(name,order_id) values('sales',(checkout_cart(pg_temp.customer_id(),pg_temp.cart(),quote_cart(pg_temp.customer_id(),pg_temp.cart()),gen_random_uuid())->>'order_id')::uuid);
update workflow_state set result=request_order_action(order_id,'cancel_submitted','Sales cancellation',key) where name='sales';
select is((select result->>'outcome' from workflow_state where name='sales'),'cancelled','Assigned Sales uses same cancellation');
reset role;
update customers set created_by=auth.uid(),assigned_sales_operator_id=null where id=pg_temp.customer_id();
set local role authenticated;
select throws_ok($$select order_workflow_state(order_id) from workflow_state where name='sales'$$,'42501',null::text,'Creator-only Sales cannot read workflow');
select throws_ok($$select request_order_action(order_id,'cancel_submitted','Sales cancellation',key) from workflow_state where name='sales'$$,'42501',null::text,'Revoked Sales cannot replay receipt');
reset role;
update customers set assigned_sales_operator_id=auth.uid(),active=false where id=pg_temp.customer_id();
set local role authenticated;
select throws_ok($$select order_workflow_state(order_id) from workflow_state limit 1$$,'42501',null::text,'Inactive customer denies Sales');
reset role;
update customers set active=true where id=pg_temp.customer_id();
update profiles set active=false where id=auth.uid();
set local role authenticated;
select throws_ok($$select order_workflow_state(order_id) from workflow_state limit 1$$,'42501',null::text,'Inactive Sales denied');
reset role;
select set_config('request.jwt.claim.sub','30000000-0000-4000-8000-000000000003',true);
set local role authenticated;
select throws_ok($$select order_workflow_state(order_id) from workflow_state limit 1$$,'42501',null::text,'Warehouse gets no price workflow access');
select throws_ok($$select request_order_action(order_id,'request_change','Denied',gen_random_uuid()) from workflow_state limit 1$$,'42501',null::text,'Warehouse cannot write workflow');
select set_config('request.jwt.claim.sub','30000000-0000-4000-8000-000000000004',true);
select throws_ok($$select request_order_action(order_id,'request_change','Denied',gen_random_uuid()) from workflow_state limit 1$$,'42501',null::text,'Accounting cannot write workflow');
select set_config('request.jwt.claim.sub','30000000-0000-4000-8000-000000000006',true);
select ok(exists(select 1 from order_change_requests where order_id=(select order_id from workflow_state where name='request')),'Manager retains RLS request reading');
select throws_ok($$update order_change_requests set status='approved',decided_by=auth.uid(),decided_at=now()$$,'42501',null::text,'Manager cannot bypass pending compensation contract');
reset role;
set local role anon;
select throws_ok($$select order_workflow_state('35000000-0000-4000-8000-000000000001')$$,'42501',null::text,'Anonymous workflow closed');
select throws_ok($$select request_order_action('35000000-0000-4000-8000-000000000001','request_change','Denied',gen_random_uuid())$$,'42501',null::text,'Anonymous write closed');
reset role;
select ok(not has_table_privilege('authenticated','private.order_workflow_receipts','SELECT'),'Private receipts not readable');
-- Repricing/unit changes after checkout must not change cancellation stock.
select set_config('request.jwt.claim.sub','30000000-0000-4000-8000-000000000001',true);
set local role authenticated;
insert into workflow_state(name,order_id) values('historical',(checkout_cart(pg_temp.customer_id(),pg_temp.cart(),quote_cart(pg_temp.customer_id(),pg_temp.cart()),gen_random_uuid())->>'order_id')::uuid);
reset role;
update product_units set conversion_to_base=24 where product_id=(select id from products where sku='TEST-A') and unit_name='koli';
update products set unit_price_kurus=15000 where sku='TEST-A';
set local role authenticated;
select lives_ok($$select request_order_action(order_id,'cancel_submitted','Historical conversion',key) from workflow_state where name='historical'$$,'Cancellation ignores changed current prices and conversion');
reset role;
select is((select sum(quantity) from inventory_movements where type='released' and reference_id=s.order_id),13::numeric,'Release uses original 1+12 base quantity, not new 1+24') from workflow_state s where name='historical';
update product_units set conversion_to_base=12 where product_id=(select id from products where sku='TEST-A') and unit_name='koli';
set local role authenticated;
insert into workflow_state(name,order_id) values('rollback',(checkout_cart(pg_temp.customer_id(),pg_temp.cart(),quote_cart(pg_temp.customer_id(),pg_temp.cart()),gen_random_uuid())->>'order_id')::uuid);
reset role;
-- Deliberately inconsistent last item: first item can be released, then second
-- must abort the entire transaction (including that first release and audit).
insert into inventory_movements(warehouse_id,product_id,type,quantity,physical_delta,reserved_delta,order_item_id,created_by,operation_key)
select i.warehouse_id,l.product_id,'released',1,0,-1,l.id,auth.uid(),gen_random_uuid()
from order_items l join inventory i on i.product_id=l.product_id
where l.order_id=(select order_id from workflow_state where name='rollback') order by l.product_id desc,l.id desc limit 1;
update inventory set reserved_qty=reserved_qty-1 where product_id=(select id from products where sku='TEST-A');
set local role authenticated;
select throws_ok($$select request_order_action(order_id,'cancel_submitted','Rollback all',key) from workflow_state where name='rollback'$$,'23514',null::text,'Inconsistent second item refuses whole cancellation');
select is((select status::text from orders where id=s.order_id),'submitted','Failed cancellation retains submitted state') from workflow_state s where name='rollback';
reset role;
select is((select count(*) from inventory_movements where order_item_id in(select id from order_items where order_id=s.order_id) and type='released'),1::bigint,'Only injected release remains; earlier loop write rolled back') from workflow_state s where name='rollback';
select is((select reserved_qty::numeric from inventory i join products p on p.id=i.product_id where p.sku='TEST-A'),28::numeric,'Partial cancellation inventory change rolled back');
select is((select count(*) from order_status_history where order_id=s.order_id),1::bigint,'Failed cancellation appends no history') from workflow_state s where name='rollback';
select is((select count(*) from private.order_workflow_receipts where operation_key=s.key),0::bigint,'Failed transaction stores no receipt') from workflow_state s where name='rollback';
select is((select count(*) from audit_logs where action='stock_movement' and entity_id in(select id from inventory_movements where order_item_id in(select id from order_items where order_id=s.order_id))),2::bigint,'Only initial two reservation audits remain') from workflow_state s where name='rollback';
select * from finish();
rollback;
